### ISSUE TITLE
setAttributes not working

### ISSUE THREAD

**Issue by samchienGG** [netless-io/netless-iframe-bridge#57]
setAttributes 切換課件報以下錯誤
TypeError: Cannot set property url of #<js> which has only a getter
我改用 updateAttributes 可以執行
不確定這樣是否是正確解法

**Comment by l1shen** [comment]
感谢反馈，确认是一个 bug, 已经发布了 `@netless/iframe-bridge@2.1.8` 修复这个问题

**Comment by samchienGG** [comment]
感謝，可以執行了
