### ISSUE TITLE
請問 iframe 有沒有可能載入太多頁導致失敗

### ISSUE THREAD

**Issue by samchienGG** [netless-io/netless-iframe-bridge#58]
我有遇過狀況
whiteWebSdk.joinRoom 有加入成功
但學生端 iframe 沒有同步出來
只可以看到白板上的字
不知道是不是有同步頁數上限

**Comment by l1shen** [comment]
插件只负责同步 url 到其他端，iframe 本身能不能加载成功还是要看这个网页本身的加载情况

**Comment by samchienGG** [comment]
那請問一下
我有一個身份是用機器開的，主要是負責錄影
有時候會沒有錄到 iframe 的狀況
原本以為是加入白板失敗
直到有次看到白板有寫字
所以才猜測是否是 iframe 的問題
我要從哪裡可以確實知道 iframe 初始成功或失敗
或是加載成功或失敗
感謝

**Comment by l1shen** [comment]
> 那請問一下 我有一個身份是用機器開的，主要是負責錄影 有時候會沒有錄到 iframe 的狀況 原本以為是加入白板失敗 直到有次看到白板有寫字 所以才猜測是否是 iframe 的問題 我要從哪裡可以確實知道 iframe 初始成功或失敗 或是加載成功或失敗 感謝

可以通过监听 IframeLoad 事件来知道 iframe load 是否成功
```ts
IframeBridge.emitter.on("IframeLoad", () => {
   // iframe load event
})
```

**Comment by samchienGG** [comment]
這邊的載入成功是指 iframe 內容載完嗎？
我要如何取到失敗狀態呢

**Comment by l1shen** [comment]
> 這邊的載入成功是指 iframe 內容載完嗎？ 我要如何取到失敗狀態呢

是的，是指 iframe 内容加载完成
失败的话本身是没有事件触发的，只能通过定时器来判断，如果一段时间内没有触发加载成功事件，就认为这个 iframe 加载失败了

**Comment by samchienGG** [comment]
感謝，我再試試看
